server:
  port: 5621
spring:
  datasource:
    url: jdbc:mysql://139.199.15.231:3306/optimal_tao?useSSL=FALSE&serverTimezone=GMT%2B8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: liao1996
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

